代码/Htest01/Htest01/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # 使用 include() 将 users 应用的 urls 模块包含进来
    path('users/', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

代码/Htest01/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('add/', views.add, name='add'),
]

代码/Htest01/users/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=50)
    # upload_to 指定上传文件位置
    # 这里指定存放在 img/ 目录下
    headimg = models.FileField(upload_to="img/")

    # 返回名称
    def __str__(self):
        return self.name

代码/Htest01/users/forms.py
# users/forms.py
from django import forms

# 表单类用以生成表单
class AddForm(forms.Form):
    # name = forms.CharField()
    headimg = forms.FileField(label="图片",max_length=500)

代码/Htest01/users/views.py
# users/views.py

from django.shortcuts import render
from .models import User
from .forms import AddForm
from . import test

# Create your views here.
def add(request):
    # 判断是否为 post 方法提交
    if request.method == "POST":
        af = AddForm(request.POST, request.FILES)
        # 判断表单值是否和法
        if af.is_valid():
            ctx = {}
            bf = AddForm()
            ctx['form'] = bf

            # name = af.cleaned_data['name']
            name = None
            headimg = af.cleaned_data['headimg']

            answer = test.predict(headimg)

            user = User(name=name, headimg=headimg)
            user.save()
            # answer = test.predict(str(headimg))

            ctx['user'] = user
            ctx['answer'] = answer
            return render(request, 'users/index.html', context={"ctx": ctx})

    else:
        ctx = {}
        af = AddForm()
        ctx['form'] = af
        ctx['headimg'] = None
        ctx['result'] = None
        ctx['accuracy'] = None
        return render(request, 'users/index.html', context={"ctx": ctx})

代码/Htest01/templates/users/index.html
<!-- templates/users/index.html -->
<!doctype html>
<html>
<head>
    <title>猫狗大战</title>
    <meta charset="utf-8">
    <link href="../../static/css/main.css" rel="stylesheet" type="text/css">
</head>
<body>
    <div id="head">
        <div id="title"><a>是猫还是狗</a></div>
    </div>

    <div id="body">

        {% if ctx.time != 0 %}
            <div id="answer_container">
                <div id="prediction">
                    <ul><li>{{ ctx.answer.result }}</li></ul>
                </div>
                <div>
                    <img id="select_img" src="/media/{{ ctx.user.headimg }}">
                </div>
            </div>
        {% endif %}

        <div id="form_container">
            <form method="post" enctype="multipart/form-data" action="{% url 'users:add' %}">
                {% csrf_token %}
                {{ ctx.form }}
                <input type="submit" value="确认"/>
            </form>
        </div>
    </div>
</body>
</html>